# Generated by Django 5.0.4 on 2024-04-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="datecompleted",
            field=models.DateTimeField(null=True),
        ),
    ]
